name: build-test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "scripts/*"
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Deno dependencies
        run: deno install

      - name: Build Deno application
        run: deno task bundle && deno task compile:linux

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-gnu

      - name: Build Rust application
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Create dist
        run: |
          mkdir -p dist/x86_64-unknown-linux-gnu
          cp build/xdwlan-login-worker dist/x86_64-unknown-linux-gnu/
          cp target/x86_64-unknown-linux-gnu/release/xdwlan-login dist/x86_64-unknown-linux-gnu/
          cp config.example.yaml dist/x86_64-unknown-linux-gnu/config.yaml
          tar cf - -C dist x86_64-unknown-linux-gnu | xz -z > dist/x86_64-unknown-linux-gnu.tar.xz

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-unknown-linux-gnu.tar.xz
          path: dist/x86_64-unknown-linux-gnu.tar.xz

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Deno dependencies
        run: deno install

      - name: Build Deno application
        run: deno task bundle && deno task compile:windows

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-pc-windows-msvc

      - name: Build Rust application
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Create dist
        run: |
          New-Item -ItemType Directory -Path dist/x86_64-pc-windows-msvc
          Copy-Item build/xdwlan-login-worker.exe -Destination dist/x86_64-pc-windows-msvc/
          Copy-Item target/x86_64-pc-windows-msvc/release/xdwlan-login.exe -Destination dist/x86_64-pc-windows-msvc/
          Copy-Item config.example.yaml -Destination dist/x86_64-pc-windows-msvc/config.yaml
          Compress-Archive -Path dist/x86_64-pc-windows-msvc -DestinationPath dist/x86_64-pc-windows-msvc.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-pc-windows-msvc.zip
          path: dist/x86_64-pc-windows-msvc.zip
