name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".vscode/**"
      - "scripts/**"
      - "README.md"
      - ".env.example"
      - ".gitignore"
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".vscode/**"
      - "scripts/**"
      - "README.md"
      - ".env.example"
      - ".gitignore"
  workflow_dispatch:
  workflow_call:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.14"

      - name: Install bun dependencies
        run: bun install

      - name: Typecheck package
        run: bun run -F xdwlan-login typecheck

  build-linux:
    runs-on: ubuntu-22.04 # Build on slightly old machine for better GLIBC compatibility.
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.14"

      - name: Install bun dependencies
        run: bun install

      - name: Build application
        run: bun run -F xdwlan-login build:linux

      - name: Create dist
        run: |
          mkdir -p dist/xdwlan-login-x86_64-unknown-linux-gnu dist/xdwlan-login-x86_64-unknown-linux-musl
          cp config.example.yaml dist/xdwlan-login-x86_64-unknown-linux-gnu/config.yaml
          cp config.example.yaml dist/xdwlan-login-x86_64-unknown-linux-musl/config.yaml
          cp packages/xdwlan-login/build/xdwlan-login-linux-gnu dist/xdwlan-login-x86_64-unknown-linux-gnu/xdwlan-login
          cp packages/xdwlan-login/build/xdwlan-login-linux-musl dist/xdwlan-login-x86_64-unknown-linux-musl/xdwlan-login
          tar cf - -C dist xdwlan-login-x86_64-unknown-linux-gnu | xz > dist/xdwlan-login-x86_64-unknown-linux-gnu.tar.xz
          tar cf - -C dist xdwlan-login-x86_64-unknown-linux-musl | xz > dist/xdwlan-login-x86_64-unknown-linux-musl.tar.xz

      - name: Upload GNU artifact
        uses: actions/upload-artifact@v7
        with:
          name: linux-gnu-artifact
          path: dist/xdwlan-login-x86_64-unknown-linux-gnu.tar.xz
          retention-days: 7

      - name: Upload musl artifact
        uses: actions/upload-artifact@v7
        with:
          name: linux-musl-artifact
          path: dist/xdwlan-login-x86_64-unknown-linux-musl.tar.xz
          retention-days: 7

  build-windows:
    runs-on: windows-latest
    env:
      TARGET: "x86_64-pc-windows-msvc"
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.14"
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ env.TARGET }}

      - name: Install bun dependencies
        run: bun install

      - name: Build bun app (login server)
        run: bun run -F xdwlan-login build:windows

      - name: Build tray ui app
        run: cargo build --release --target $env:TARGET

      - name: Create dist
        run: |
          New-Item -ItemType Directory -Path dist/xdwlan-login-x86_64-pc-windows-msvc
          Copy-Item config.example.yaml -Destination dist/xdwlan-login-x86_64-pc-windows-msvc/config.yaml
          Copy-Item target/$env:TARGET/release/xdwlan-login.exe -Destination dist/xdwlan-login-x86_64-pc-windows-msvc
          Compress-Archive -Path dist/xdwlan-login-x86_64-pc-windows-msvc -DestinationPath dist/xdwlan-login-x86_64-pc-windows-msvc.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: windows-artifact
          path: dist/xdwlan-login-x86_64-pc-windows-msvc.zip
          retention-days: 7
